# HiggsML pipeline configuration
data_source: higgs
data_dir: data/HiggsML/input_data/train
mu: 1.0
seed: 18
threshold: 0.5
mu_hat_mode: mle               # "raw" or "mle"
interval_mode: symmetric       # "symmetric" or "free_form"
nonconf_target: mu_hat         # "mu_hat" or "n_pred"
output_dir: higgs-{mu_hat_mode}-{interval_mode}-{train_size}train-{valid_size}valid-{ref_size}ref-{calib_size}calib-{test_size}test
fit_parallel: false
valid_size: 10
calib_size: 10

# higgs-specific
train_size: 10
ref_size: 10
test_size: 10
block_size: 10000
