# HiggsML pipeline configuration
data_source: higgs
data_dir: data/HiggsML/input_data/train
mu: 1.0
seed: 20260330
threshold: 0.5
how: abs                        # "diff" or "abs"
nonconf_target: mu_hat          # "mu_hat" or "n_pred"
output_dir: higgs-q68-1train-1valid-1ref-1calib-1test
fit_parallel: false
valid_size: 1
calib_size: 1

# higgs-specific
train_size: 1
ref_size: 1
test_size: 1
block_size: 1000
